### ISSUE TITLE
undefined reference to '__fgets_chk' compile with glibc-2.35

### ISSUE THREAD

**Issue by myhou0418** [intel/intel-sgx-ssl#125]
Hi, An error occurred when I'am compiling the source code of intel-sgx-ssl 2.15.1.
![image](https://user-images.githubusercontent.com/24760533/174246006-fc6c9803-b386-40bd-9c2d-30eeacbde859.png)

After analyze，the error is caused by glibc-2.35 some changes
https://github.com/bminor/glibc/commit/a643f60c53876be0d57b4b7373770e6cb356fd13
![image](https://user-images.githubusercontent.com/24760533/174246587-059d1b64-eaf2-49d1-9d83-f395006a6554.png)

But I don't know how to fix.
Does the community have any suggestions for this error? 
Thanks!

**Comment by jinghe-INTC** [comment]
Can you check the file `openssl/opensslconf.h` in your build path, and try to find:

```
#ifndef OPENSSL_NO_STDIO
# define OPENSSL_NO_STDIO
#endif
```
in it? It is supposed to make the `crypto/bio/bss_file.c:file_gets()` be defined as:
```
 static int file_gets(BIO *bp, char *buf, int size)
{
        return 0;
}
```
not the other one which calls fgets() and causes the problem you met.

**Comment by jinghe-INTC** [comment]
Hi @myhou0418,
Do you still have the problem? Otherwise I will close the issue.

**Comment by jinghe-INTC** [comment]
The issue is being closed now. You can reopen it if necessary.
